app:
  name: Daily Assistant Application
  description: Application for supporting daily routine - calendar, events, tasks, and notes.
  version: 1.0.0

spring:
  profiles:
    active: dev, sqlite

  server:
    port: 8080
    servlet:
      context-path: /api

  datasource:
    url: jdbc:h2:mem:db
    driver-class-name: org.h2.Driver
    username: sa
    password:

  secondary:
    url: jdbc:sqlite:db
    driver-class-name: org.sqlite.JDBC
    jpa:
      database-platform: org.hibernate.dialect.SQLiteDialect

  jpa:
    show-sql: true

  properties:
    hibernate.dialect: org.hibernate.dialect.H2Dialect

    hibernate:
      ddl-auto: update

  h2:
    console:
      enabled: true

  cache:
    host: localhost
    port: 6379

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.cache: DEBUG
    org.springframework.http.converter: DEBUG

  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
