app:
  name: OpenCalendar Application
  description: Application for supporting daily routine.
  version: 1.0.0

spring:
  cache:
    redis:
      host: ${SPRING_CACHE_HOST:localhost}
      port: ${SPRING_CACHE_PORT:6379}
      time-to-live: 300000

jwt:
  secret: ${SPRING_JWT_SECRET_KEY}

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.cache: DEBUG
    org.springframework.http.converter: DEBUG

  pattern:
    console: "[%d{yyyy-MM-dd HH:mm:ss}] [%level] [%logger{24}] - %msg%n"
