spring:
  datasource:
    url: jdbc:sqlite:database/production.sqlite
    driver-class-name: org.sqlite.JDBC

  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    show-sql: true
    hibernate:
      ddl-auto: none

  sql:
    init:
      mode: always
      platform: sqlite
