app:
  name: Daily Assistant Application
  description: Monolithic application for supporting daily routine - calendar, events, tasks, and notes.
  version: 1.0.0
spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.http.converter: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
