name: Automatically Update Dependencies

on:
  schedule:
    - cron: "0 3 * * 1"
  workflow_dispatch:

jobs:
  update-dependencies:
    name: Automatic Gradle Dependencies Update
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: temurin

      - name: Refresh Versions
        run: ./gradlew refreshVersionsUpdate

      - name: Generate Dependency Update Report
        run: ./gradlew dependencyUpdates -Drevision=release

      - name: Commit and Push if Updates Needed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git diff-index --quiet HEAD || git commit -m "chore: auto-update Gradle dependencies"
          git push
