name: Run Tests

on:
  workflow_dispatch:

jobs:

  checkout:
    name: Checkout Repository
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

  setup-java:
    name: Set Up JDK
    needs: checkout
    runs-on: ubuntu-latest
    steps:
      - name: Set Up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin

  run-tests:
    name: Run Tests
    needs: setup-java
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin

      - name: Run Tests
        run: ./gradlew test --stacktrace

      - name: Publish JUnit Test Report to GitHub UI
        if: always()
        uses: dorny/test-reporter@v1
        with:
          name: JUnit Tests
          path: build/test-results/test/TEST-*.xml
          reporter: java-junit

      - name: Upload JUnit HTML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit-html-report
          path: build/reports/tests/test
