name: Synchronize Production to Main

on:
  push:
    branches:
      - production

jobs:
  synchronization:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Production
        uses: actions/checkout@v4
        with:
          ref: production
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to main
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git push origin production:main --force
